// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZoGKDbYuj6x5BqEt2PFx2_shwerl2EU',
    appId: '1:23595213811:web:3d281d9d417b32918b6886',
    messagingSenderId: '23595213811',
    projectId: 'myvideobucket-d2271',
    authDomain: 'myvideobucket-d2271.firebaseapp.com',
    storageBucket: 'myvideobucket-d2271.appspot.com',
    measurementId: 'G-0YY209WE3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV0cnne26KEfCYBdoYqogwqoPAqgqKwa4',
    appId: '1:23595213811:android:2ae7884722ababd98b6886',
    messagingSenderId: '23595213811',
    projectId: 'myvideobucket-d2271',
    storageBucket: 'myvideobucket-d2271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0L3GZvFBANLQxIjNcxrB2VUQcJsHjPz0',
    appId: '1:23595213811:ios:ff88f107b4464afb8b6886',
    messagingSenderId: '23595213811',
    projectId: 'myvideobucket-d2271',
    storageBucket: 'myvideobucket-d2271.appspot.com',
    iosClientId: '23595213811-ha5uo9vp02jubp3nevsj7hffhbtk0scm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPhotoBucket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0L3GZvFBANLQxIjNcxrB2VUQcJsHjPz0',
    appId: '1:23595213811:ios:ff88f107b4464afb8b6886',
    messagingSenderId: '23595213811',
    projectId: 'myvideobucket-d2271',
    storageBucket: 'myvideobucket-d2271.appspot.com',
    iosClientId: '23595213811-ha5uo9vp02jubp3nevsj7hffhbtk0scm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPhotoBucket',
  );
}
