// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacvBeyFDdH_v09YoOODY20kcySDE606Y',
    appId: '1:553050929411:web:1c5a6a9468ab92a2921136',
    messagingSenderId: '553050929411',
    projectId: 'finalproject-dir',
    authDomain: 'finalproject-dir.firebaseapp.com',
    storageBucket: 'finalproject-dir.appspot.com',
    measurementId: 'G-R1HB4CL6SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClv3S1cfYs0tvFN2bQrCL4yu26hl9Qusc',
    appId: '1:553050929411:android:3cc78a68566e6910921136',
    messagingSenderId: '553050929411',
    projectId: 'finalproject-dir',
    storageBucket: 'finalproject-dir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsmIKBOFN4ecxTuYWGGTJlrHdCfRv2UCw',
    appId: '1:553050929411:ios:6ea6528b9d5811fd921136',
    messagingSenderId: '553050929411',
    projectId: 'finalproject-dir',
    storageBucket: 'finalproject-dir.appspot.com',
    iosClientId: '553050929411-s9d14ikl7juv2d64692rc5rn8pa9btqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsmIKBOFN4ecxTuYWGGTJlrHdCfRv2UCw',
    appId: '1:553050929411:ios:6ea6528b9d5811fd921136',
    messagingSenderId: '553050929411',
    projectId: 'finalproject-dir',
    storageBucket: 'finalproject-dir.appspot.com',
    iosClientId: '553050929411-s9d14ikl7juv2d64692rc5rn8pa9btqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjDart',
  );
}
